### ISSUE TITLE
Only allow network activation

### ISSUE THREAD

**Issue by Zodiac1978** [webgilde/individual-multisite-author#16]
**Summary**

It looks like this only makes sense if enabled on a multisite, so you can activate Network activation.

Current solution
---

If you add this line to the readme.txt header the network activation is enabled:

`Network:     true`

Expected behavior
---

Network: Whether the plugin can only be activated network-wide. Can only be set to true, and should be left out when not needed.
Source: https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

**Comment by webzunft** [comment]
Thanks @Zodiac1978, I didn’t know that!

**Comment by webzunft** [comment]
I tested this and I think `Network` means something different.
As the linked resource says:
> Whether the plugin can only be activated network-wide. Can only be set to true, and should be left out when not needed.

It means that the plugin can only be activated for all sites, not on individual sites. It doesn’t prevent the plugin from being enabled on a non-multisite.
If I added this header field, users would not be able to use the plugin only on certain sites in the network.

**Comment by Zodiac1978** [comment]
Then I misunderstood your plugin use case. I thought it is only useful/meant to be activated network wide.

If it is meant to be used on single sites in a multisite environment then this addition makes obviously no sense.

Sorry for the interruption!
